---
- name: Update and upgrade SO packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
 
- name: "Install Nginx"
  ansible.builtin.apt:
    name: "nginx={{ nginx_version }}"
    state: present
 
- name: Copy configuration
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Create link to nginx configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link
 
- name: Nginx custom directory
  ansible.builtin.file:
    path: "{{ custom_directory }}"
    state: directory
 
- name: Copy index.html to the Nginx directory
  when: default_index == True
  copy:
    src: files/index.html
    dest: "{{ custom_directory }}/index.html"
  notify: Restart Nginx

- name: Create custom index.html to the Nginx directory
  when: default_index == False
  template:
    src: templates/index.html.j2
    dest: "{{ custom_directory }}/index.html"
  notify: Restart Nginx
