---
- name: Provision docker using role
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  roles:
  - role: "roles/docker"

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:  
  - name: Copy directory to remote host
    copy:
      src: "{{ playbook_dir }}/../app/"
      dest: "/opt/app/"
  - name: Build docker image
    ansible.builtin.command:
      cmd: docker compose up -d
      chdir: /opt/app